version: '3.7'

services:

  # Add mysql
  mariadb-service:
    container_name: mariadb-container
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password

  # Add phpmyadmin
  phpmyadmin-service:
    container_name: phpmyadmin-container
    image: phpmyadmin
    restart: always
    # Expose phpmyadmin to localhost:8098
    ports:
      - 8098:80
    environment:
      PMA_HOST: mariadb-service
    links:
      # Wait for mariadb to setup
      - mariadb-service

  # Add php
  php-service:
    container_name: php-container
    build:
      context: ./
      dockerfile: php/Dockerfile
    expose:
      - 9000
    volumes:
      - ./app/public/upload:/app/public/upload
    links:
      # Wait for mariadb to setup
      - mariadb-service

  # Add nginx
  nginx:
    container_name: nginx-container
    image: nginx:alpine
    # Expose the server to localhost:8000
    ports:
      - 8000:80
    volumes:
      # Share local app folder on /app in container
      - ./app:/app
      # Save nginx logs in /nginx/logs
      - ./nginx/logs:/var/log/nginx
      # Set the default.conf file in container
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      # Wait for php to setup
      - php-service
